services:
  jiotv_go:
    image: ghcr.io/jiotv-go/jiotv_go
    ports:
      - "5001:5001"
    volumes:
      - .jiotv_go:/app/.jiotv_go
    environment:
      - JIOTV_PATH_PREFIX=/app/.jiotv_go
      - JIOTV_EPG=true
      - TZ=Asia/Kolkata
      - JIOTV_DRM=false

